### PR TITLE
Moved ExternalParserTarget loading into Body class

### PR DESCRIPTION
**Pull request by HappyFaceIndustries**
This moves the ExternalParserTarget loading code out of the Parser class and into the Body class so that there are no weird static values being referenced, and so that it is guaranteed that ExternalParserTargets will load after everything else.

Also, I'm not sure how to submit a pull request without the changes to Kopernicus.csproj

### CODE REVIEW

**Comment by ArnePeirs** [comment]
If you use an external program for GitHub you can discard changes / ignore a file before pushing to a repo.

But no worries, your changes for the .csproj aren't breaking

**Comment by Kerbas-ad-astra** [comment]
You can "stash" modifications without committing them. (Seriously, the command is "git stash".)

**Comment by ThomasKerman** [comment]
I have to merge this manually, because of some weird GitHub issues. Looks pretty solid.

**Comment by ThomasKerman** [comment]
@Teknoman117 what do you think about the new code? I couldn't find any bugs, so I'd like to include it into the next Kopernicus Version. :)

**Comment by HappyFaceIndustries** [comment]
I've been testing it out, and I haven't encountered any issues. That's what [this](http://forum.kerbalspaceprogram.com/threads/114649-1-0-4-Kopernicus-Beta-%280-2-4%29-July-24?p=2115559#post2115559) was.

**Pull request closed without merging**
