### PR TITLE
Implemented star alternator

### PR DESCRIPTION
**Pull request by ThomasKerman**
To be honest, I don't understand the Kopernicus cfg-Loader.... Nevermind, stars are now fully customizable via. StarColor node. http://i.imgur.com/49Uj5ok.jpg

I hope you will like my way to implement this. :)

### CODE REVIEW

**Comment by ThomasKerman** [comment]
I've updated my master brach with a ring loader, simlar to Kittiopas RingTools. Could you maybe check this too? http://i.imgur.com/uQLjT73.jpg

(And I've finally understood the Kopernicus Node-loader :D)

**Comment by Teknoman117** [comment]
Will do.

**Comment by Teknoman117** [comment]
I'll be editing this code for inclusion in the configuration loader.  I'll also pull the ring loader into a development branch.  I haven't stepped through it completely yet, but if its not done properly, the ring will also disappear when on the surface (since the scaled version gets faded as the PQS version becomes visible.)

**Comment by ThomasKerman** [comment]
The ring appears only on Gas planets, as far as I can see, but he isn't disappearing, when switching from ScaledSpace to LocalSpace. Maybe I can enhance this. And I will try to move the Star code myself today (in about 10 hours). We'll see, who of us finishes first..

**Comment by Teknoman117** [comment]
I suppose I've beat you to it.  See https://github.com/BryceSchroeder/Kopernicus/commit/373b7f80d46efb3e9a455851b4e4d43610c3ea9f

The most notable changes - powerCurve was renamed to SolarPowerCurve.  Same key-value functionality as before.  The customized settings are stored in a custom component added to the scaled space version of the star (power curve and light color).  The star material modifications were dropped as this functionality already existed (you could specify material option overrides for scaled space).  A coronas list node was added for creating custom coronas.  I've updated the Nemesis example accordingly.

**Comment by Teknoman117** [comment]
You wanna convert star systems mod into a Kopernicus config file tomorrow?  Considering the requirements have now been satisfied... Check out the development branch in the master repo

**Comment by ThomasKerman** [comment]
Thanks! My original plan was to look into PQS, but maybe I'll put together a StarSystems cfg before that.

----- Ursprüngliche Nachricht -----
Von: "Nathaniel Lewis" <notifications@github.com>
Gesendet: ‎24.‎03.‎2015 08:43
An: "BryceSchroeder/Kopernicus" <Kopernicus@noreply.github.com>
Cc: "Dorian Stoll" <dorianstoll@googlemail.com>
Betreff: Re: [Kopernicus] Implemented star alternator (#17)

You wanna convert star systems mod into a Kopernicus config file tomorrow? Considering the requirements have now been satisfied... Check out the development branch in the master repo

**Comment by Teknoman117** [comment]
If you could do me a favor and hold off on the PQS until tomorrow, there a still one or two things I need to do.  For instance, I don't remember if I completed the parser's ability to load lists where the node name was the class type.  I would, however, familiarize yourself with the whole PQSMod system.  Just use the Assembly browser to pick through them.

**Comment by ThomasKerman** [comment]
I've done that already and looked into VertexHeightMap, the mod on that I'm going to test all the stuff first. However, one question about applying them to the Body: I need to grab the GameObject of the CelestialBodyTransform and add the PQSMod to it, correct? 

----- Ursprüngliche Nachricht -----
Von: "Nathaniel Lewis" <notifications@github.com>
Gesendet: ‎24.‎03.‎2015 17:09
An: "BryceSchroeder/Kopernicus" <Kopernicus@noreply.github.com>
Cc: "Dorian Stoll" <dorianstoll@googlemail.com>
Betreff: Re: [Kopernicus] Implemented star alternator (#17)

If you could do me a favor and hold off on the PQS until tomorrow, there a still one or two things I need to do. For instance, I don't remember if I completed the parser's ability to load lists where the node name was the class type. I would, however, familiarize yourself with the whole PQSMod system. Just use the Assembly browser to pick through them.

**Comment by Teknoman117** [comment]
Basically, here's what needs to be done

-> Complete ParserTargetCollection's support of "key is type" support (see Parser.cs:220).  IIRC, we need to figure out the namespace of the class somehow.  This enables a collection to be specified like this
[ParserTargetCollection("Mods", optional = true, nameSignificance = NameSignificance.Type)]
private List<object> mods = new List<object>();

// It would mean that in the config, if someone put 
Mods
{
    // An object of type "Mod_VertexHeightMap" would be instantiated and added to the mods list
    Mod_VertexHeightMap
    {
    // the important stuff
    }
}

-> Material Wrapper Loaders need to be written for the PQS surface materials.  See all of the PQS*.cs classes in Kopernicus/MaterialWrapper.  These were generated from a little tool I wrote to translate Unity .shader files into these wrapper materials.  We need some way to resolve them since it could be the PQSMainOptimized shader, the PQSProjectionAerialQuadRelative shader, the PQSProjectSurfaceQuad shader, or any of the fallback shaders.  I suppose I can do this later today 

-> The current skeleton of the PQSLoader is in PQSLoader.cs.  It either goes with an existing PQS -or- it generates one from scratch and applied the base required PQS mods.  There are other things we need to add, such as the min and max LOD levels.  There is also sub-pqs versions for oceans and stuff.  When done, I suspect the config file look like this

Body 
{
    PQS
    {
        minLevel = 2
        maxLevel = 8
        
        Material
        {
             // PQS material options.  These include all of the terrain textures for different lat/long, slopes, etc.
        }
        
        Mods
        {
             // ALL THE MODS!!!
        }
    }
}

-> Last is something that not many like doing.  We have to freaking document everything so that people understand whats going on...

**Comment by Teknoman117** [comment]
I actually have time this morning.  Do you mind pushing what you have right now?

**Comment by ThomasKerman** [comment]
Okay, thanks. I've set up a new PQS branch on my fork, should I give you write access? That would eliminate the pull-merge-pull-merge "tactic". :)  

So, according to your explanation, I'll try to write a generic "PQSMod" loader, that dumps all the variables into a file. :)

**Comment by Teknoman117** [comment]
That works?

**Comment by ThomasKerman** [comment]
What are you trying to say?

**Comment by Teknoman117** [comment]
* Sorry, giving me write access is fine.

**Comment by ThomasKerman** [comment]
Sure, it's done. (I'm no native english speaker, so please don't wonder if I don't understand something. :))

**Pull request merged**
