### PR TITLE
Added some PQS mods

### PR DESCRIPTION
**Pull request by Gravitasi**
I have added some loader for PQS mods. Not really sure about what to put in ModifierRequirements, since there are no stock planets that use any of the mods. Nevertheless, so far they work correctly.

I will add some more in the future.

Thanks.

### CODE REVIEW

**Comment by Teknoman117** [comment]
I actually just discovered that setting the requirements isn't necessary, for the PQS mods set them themselves when they are started.

**Comment by ThomasKerman** [comment]
I've never specified them :D
Also, could you look into my development branch Tekno? I've added "some" Mods. :)

**Comment by Teknoman117** [comment]
Already did

**Comment by Teknoman117** [comment]
Currently working on fixing the SOI bug.  Also, at some point we are going
to have to go through and document everything.  And provide examples (with
pictures)....

**Pull request merged**
