### PR TITLE
ExternalParserTargets, adding ParserTargets from other assemblies

### PR DESCRIPTION
**Pull request by HappyFaceIndustries**
I added a small bit to the Parser that looks for classes in all the loaded assemblies that have the ExternalParserTarget atribute and extend ExternalParserTargetLoader, and loads them in as if they were regular ParserTargets.  
This would allow plugin developers to extend the configuration system of Kopernicus in there own plugins beyond adding custom ModLoaders.

I made an example
one that adds my glowing ocean effect, ([code here](https://gist.github.com/HappyFaceIndustries/5cf0fdc4d9805d0168c1#file-emissiveoceanloader)) and it loads flawlessly. Even when it wasn't loading flawlessly, it still didn't break the rest of Kopernicus's functionality in any way.

[Image](https://cloud.githubusercontent.com/assets/7258677/8561166/83bf8e32-24e6-11e5-86d5-ffa99ccaaba9.png)

### CODE REVIEW

**Comment by Teknoman117** [comment]
Lemme review this

**Comment by Teknoman117** [comment]
Can't read on phone well

**Comment by Teknoman117** [comment]
Could you also include some code as a simple usage example?

**Comment by Teknoman117** [comment]
Nvm I'm dumb I missed the link

**Comment by ThomasKerman** [comment]
@Teknoman117 I've imported this into a seperate branch on this respository: https://github.com/BryceSchroeder/Kopernicus/tree/ExternalLoaders 
Might be useful for easy adaption / bugfixing. :)

**Comment by Teknoman117** [comment]
Yeah I was going to do the same

**Comment by Teknoman117** [comment]
HappyFaceIndustries, do you mind uploading a complete example (like with the textures, shaders, and config?)

**Pull request closed without merging**
